### PR TITLE
Fix ceres exercise build errors

### PR DESCRIPTION
**Pull request by mleotta**
Fixed some compile and link errors

### CODE REVIEW

**Comment by mleotta** [comment]
Sameer, I can easily merge these changes, but I thought it would be best to make you aware of them first.  These are fixes I needed to build the latest Ceres exercise code in the VM.

**Comment by sandwichmaker** [comment]
Hi Matt,
I will look at this over the weekend and will land the last bits that are
needed for my exercises. IO is ALMOST over :)
Sameer

**Comment by mleotta** [comment]
Sameer,

The github pull request in just a minor thing.   Sorry to distract you from IO with it.  I could have just merged it, but I wanted you to see the changes I was making in case you are reusing those exercise outside of this tutorial or in case I’m screwing something up.

Is there some cool new Ceres related thing you are announcing at IO?

Best,
Matt

**Comment by sandwichmaker** [comment]
Thanks Matt. This is c++11/c++98 madness.

**Pull request merged**
